[[items]]
path = "https://github.com/tinted-theming/base16-waybar"
name = "base16-waybar"
themes-dir = "colors"
hook = "cp -f %f ~/.config/waybar/colors.css"

[[items]]
path = "https://github.com/tinted-theming/base16-dunst"
name = "base16-dunst"
themes-dir = "themes"
hook = 'sed -i "/# TINTY START/,/# TINTY END/{//!d}" ~/dotfiles/dunst/.config/dunst/dunstrc && sed -i "/# TINTY START/r %f" ~/.config/dunst/dunstrc'

[[items]]
path = "https://github.com/tinted-theming/base16-waybar"
name = "base16-wofi"
themes-dir = "colors"
hook = 'cp -f %f ~/.config/wofi/colors.css'

[[items]]
path = "https://github.com/kirasok/base16-hyprland"
name = "base16-hyprland"
themes-dir = "themes"
hook = 'cp -f %f ~/.config/hypr/colors.conf'
