#!/bin/bash

# Directory where the git repo will be cloned
WORK_DIR="$HOME/mesa-git-build"
# Directory where the compiled binaries will be "installed" locally
INSTALL_DIR="$HOME/mesa-git-local"
REPO_URL="https://github.com/Frogging-Family/mesa-git.git"

echo ">>> Starting mesa-git local build process..."

# 1. Prepare Workspace
mkdir -p "$WORK_DIR"
cd "$WORK_DIR" || exit

# 2. Clone or Update Repository
echo ">>> Cloning repository..."
git clone "$REPO_URL"
cd mesa-git

# 3. Build the package (Requires sudo for dependencies)
# -s: install deps, -r: remove deps after, -c: clean
# Note: You can edit customization.cfg manually before running this if you want specific drivers
echo ">>> Building packages..."
makepkg -s --noconfirm

# 4. Clean previous local install
echo ">>> Cleaning old local install..."
rm -rf "$INSTALL_DIR"
mkdir -p "$INSTALL_DIR"

# 5. Extract the built packages
# We look for .pkg.tar.zst files generated by makepkg
echo ">>> Extracting packages to $INSTALL_DIR..."
find . -name "*.pkg.tar.zst" -exec tar -I zstd -xf {} -C "$INSTALL_DIR" \;
rm -rf "$WORK_DIR"

# 6. Patch Vulkan JSON manifests
# The .json files point to absolute paths (e.g., /usr/lib/libvulkan_radeon.so).
# We must rewrite them to point to our local $INSTALL_DIR.
echo ">>> Patching Vulkan ICD manifests..."

# Find all json files in the extracted directory
find "$INSTALL_DIR" -name "*.json" | while read -r json_file; do
    # Replace /usr/lib with /home/user/mesa-local/usr/lib
    sed -i "s|/usr/lib|$INSTALL_DIR/usr/lib|g" "$json_file"
    echo ">>> Patched: $json_file"
done

echo ">>> Done! Mesa is ready at: $INSTALL_DIR"
