---
- name: Setup Arch Linux System
  hosts: localhost
  connection: local
  become: false
  vars:

    arch_packages:
      # System
      - linux-cachyos
      - linux-cachyos-headers
      - cachyos-settings
      - scx-scheds-git
      - limine-mkinitcpio-hook
      # - limine-snapper-sync
      # - snap-pac
      - xdg-desktop-portal-gtk
      # Tools
      - zsh
      - 7zip
      - ghostty
      - fuse2
      - fuse3
      - man-db
      - tealdeer
      - stow
      - downgrade
      - fzf
      - zoxide
      - ripgrep
      - fd
      - nnn-nerd
      - fastfetch
      - atool
      - flatpak
      - brightnessctl
      - amdgpu_top
      - libnotify
      - playerctl
      - btop
      - rocm-smi-lib
      - git
      - lazygit
      - unrar
      - unzip
      - yay
      - firefox
      - wine
      - pavucontrol
      - mpv
      - luarocks
      - steam
      - lizardbyte-beta/sunshine-git
      # Theming & Fonts
      - kvantum
      - nwg-look
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra
      - ttf-hack-nerd
      # Hyprland
      - xdg-desktop-portal-hyprland
      - waybar
      - hyprpaper
      - dunst
      - wofi
      - hyprlock
      - hypridle
      - grim
      - slurp
      - wl-clipboard

    aur_packages:
      - neovim-git
      - gamescope-git
      - fan2go-git
      - lact-git
      - tinty-git
      - papirus-icon-theme-git
      - bibata-cursor-theme
      - catppuccin-gtk-theme-mocha
      - gamemode-git
      - mangohud-git
      - lib32-mangohud-git
      - qt6ct-kde
      - journalctl-desktop-notification
      - arkenfox-user.js

    flatpak_packages:
      - org.qbittorrent.qBittorrent
      - org.jdownloader.JDownloader
      - com.github.Matoking.protontricks
      - com.vysp3r.ProtonPlus
      - dev.vencord.Vesktop
      - com.github.tchx84.Flatseal
      - it.mijorus.gearlever

    sys_services:
      #- {name: "limine-snapper-sync", enabled: true}
      - {name: "scx_loader", enabled: true}
      - {name: "lactd", enabled: true}
      - {name: "fan2go", enabled: true}
      - {name: "scx", enabled: false}
      - {name: "ananicy-cpp", enabled: false}

    string_blocks:
      - name: repositories
        path: /etc/pacman.conf
        block: |
          [cachyos-znver4]
          Include = /etc/pacman.d/cachyos-v4-mirrorlist

          [cachyos-core-znver4]
          Include = /etc/pacman.d/cachyos-v4-mirrorlist
          
          [cachyos-extra-znver4]
          Include = /etc/pacman.d/cachyos-v4-mirrorlist
          
          [cachyos]
          Include = /etc/pacman.d/cachyos-mirrorlist

          [chaotic-aur]
          Include = /etc/pacman.d/chaotic-mirrorlist

          [lizardbyte]
          SigLevel = Optional
          Server = https://github.com/LizardByte/pacman-repo/releases/latest/download
          
          [lizardbyte-beta]
          SigLevel = Optional
          Server = https://github.com/LizardByte/pacman-repo/releases/download/beta
      - name: edid
        path: /etc/mkinitcpio.conf.d/edid.conf
        block: |
          FILES=(/usr/lib/firmware/edid/modified-edid)
      - name: cmdline
        path: /etc/default/limine
        block: |
          KERNEL_CMDLINE["linux-cachyos"]="{{ lookup('file', '/etc/ogcmdline') }} drm.edid_firmware=HDMI-A-1:edid/modified-edid video=HDMI-A-1:e"

    stow_user_packages:
      - zsh
      - fontconfig
      - hypr
      - ghostty
      - btop
      - dunst
      - mangohud
      - nvim
      - SLSsteam
      - waybar
      - wofi
      - sunshine
      - tinty

    stow_sys_packages:
      - fan2go
      - scx_loader

    user_commands:
      - tldr --update
      - tinty sync
      - tinty apply base16-catppuccin-mocha
      - nmcli c modify 'Wired connection 1' 802-3-ethernet.wake-on-lan magic

    sys_commands:
      - limine-mkinitcpio

  tasks:
    - name: Fail if running as root
      fail:
        msg: "Don't run as root!"
      when: ansible_user_id == "root"

    - name: Add fan controller module
      modprobe:
        name: nct6775
        state: present
        persistent: present
      become: yes

    - name: Create and ensure dirs and files
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
      become: yes
      loop:
        - {path: /usr/lib/firmware/edid/, state: directory}
        - {path: ~/.config/hypr/, state: absent}

    - name: Copy config files if they do not exist
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        force: no
      become: yes
      loop:
        - {src: /etc/limine-entry-tool.conf, dest: /etc/default/limine}
        - {src: ~/dotfiles/res/modified-edid, dest: /usr/lib/firmware/edid/modified-edid}
        - {src: /proc/cmdline, dest: /etc/ogcmdline}

    - name: Add string blocks to files
      blockinfile:
        path: "{{ item.path }}"
        block: "{{ item.block }}"
        marker: "# {mark} ANSIBLE MANAGED"
        backup: yes
        create: yes
        insertbefore: 'core-testing'
      become: yes
      loop: "{{ string_blocks }}"

    - name: Repo keys
      command: "{{ item }}"
      become: yes
      loop:
        - pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
        - pacman-key --lsign-key 3056513887B78AEB
        - pacman-key --recv-keys F3B607488DB35A47 --keyserver keyserver.ubuntu.com
        - pacman-key --lsign-key F3B607488DB35A47

    - name: Repo mirror and keyrings
      pacman:
        name: "{{ item }}"
        state: present
      become: yes
      loop:
        - https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst
        - https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst
        - https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-keyring-20240331-1-any.pkg.tar.zst
        - https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-mirrorlist-22-1-any.pkg.tar.zst
        - https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-v3-mirrorlist-22-1-any.pkg.tar.zst
        - https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-v4-mirrorlist-22-1-any.pkg.tar.zst
        - https://mirror.cachyos.org/repo/x86_64/cachyos/pacman-7.0.0.r7.g1f38429-1-x86_64.pkg.tar.zst

    - name: Update system
      pacman:
        update_cache: yes
        upgrade: yes
      become: yes

    - name: Install arch packages
      pacman:
        name: "{{ arch_packages }}"
        state: present
      become: yes

    - name: Install aur packages
      pacman:
        name: "{{ aur_packages }}"
        executable: yay
        state: present

    - name: Add the flathub flatpak repository remote
      flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        state: present

    - name: Install Flatpak apps
      flatpak:
        name: "{{ flatpak_packages }}"
        state: present

    - name: Change shell
      user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh
      become: yes

    - name: Manage system services
      systemd_service:
        name: "{{ item.name }}"
        enabled: "{{ item.enabled }}"
        state: "{{ 'started' if item.enabled else 'stopped' }}"
        scope: system
      loop: "{{ sys_services }}"
      become: yes

    - name: Stow user configuration
      command: stow -t /home/{{ ansible_user_id }}/ -d /home/{{ ansible_user_id }}/dotfiles {{ item }}
      loop: "{{ stow_user_packages }}"

    - name: Stow system configuration
      command: stow -t / -d /home/{{ ansible_user_id }}/dotfiles {{ item }}
      loop: "{{ stow_sys_packages }}"
      become: yes

    - name: Run my user commands
      command: "{{ item }}"
      loop: "{{ user_commands }}"

    - name: Run my system commands
      command: "{{ item }}"
      become: yes
      loop: "{{ sys_commands }}"
